[flavor]
name = "full"
description = "Default SolarOS build with all built-in packages enabled."

[packages]
system = true
expansions = true
maintenance_apps = true
maintenance_jobs = true
hardware_jobs = true
audio = true
net = true
agent = true
media = true
games = false
python = true
lua = true
writing = true
utils = true
